x-basics: &basics
  env_file:
    - .env
  restart: unless-stopped
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: postgres
    networks:
      core:
        ipv4_address: 172.20.0.12
    <<: *basics
    environment:
      - POSTGRES_DATABASES=${POSTGRES_DATABASES}
      - POSTGRES_USERS=${POSTGRES_USERS}
      - POSTGRES_PASSWORDS=${POSTGRES_PASSWORDS}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ROOT_USERNAME-root}"]
      start_period: 60s
      timeout: 15s
      retries: 10
    volumes:
      - ./volumes/database/postgres:/var/lib/postgresql/data
      - ./services/postgres/init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
